### ISSUE TITLE
Améliorer le design 🔃

### ISSUE THREAD

**Issue by daoodaba975** [daoodaba975/add.me.in#12]
Je suis ouvert à toute suggestion pour rendre le design plus jolie 🎉

**Comment by xyhomi3** [comment]
Hello, j'aimerai proposer un design, mais Astro c'est nouveau pour moi, je crois ça vas me permettre d'en apprendre plus

**Comment by daoodaba975** [comment]
Hi @xyhomi3 oui tu peux voir la documentation de Astro si tu veux : https://docs.astro.build/en/getting-started

**Comment by xyhomi3** [comment]
Super jviens de faire un PR

**Comment by daoodaba975** [comment]
Tu peux corriger le conflit @xyhomi3 STP

**Comment by daoodaba975** [comment]
#19
